# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development: &generic
  secret_key_base: cd8ff47906f352e8116a6afafe9a90d2830e09a2fe99878d3d023c5f17a2374da2e53455e4e025bd1b4edba6d433c75c6b02540b6017f4fc43a7df42193744cf
  companies:
    "agrofor.pro": &agrofor
      id: 1
      name: agrofor
    "fuelfor.pro": &fuelfor
      id: 2
      name: fuelfor
    "woodfor.pro": &woodfor
      id: 3
      name: woodfor
    "https://agrofor.pro":
      <<: *agrofor
    "local.agrofor.pro":
      <<: *agrofor
    "local.fuelfor.pro":
      <<: *fuelfor
    "https://fuelfor.pro":
      <<: *fuelfor
    "local.woodfor.pro":
      <<: *woodfor
    "https://woodfor.pro":
      <<: *woodfor

test:
  <<: *generic
  secret_key_base: 0f9015da3a40e5a8c755463b275da16a5065e219e496dd0bfa9aeda68462605c7ce270300a55618e0d185b54994ec16095c669e30049ee27bdb0565d642202ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *generic
  secret_key_base: 3775a8d39920597cbf700c00d2162364b49fc1040ef67a3d5311315d5c327bd4773adf5acf6f9071cf88cbdc14e63a6c8644a39d3e9ce03c55f8d0484c331af7
